apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kpack-dependencies.community.tanzu.vmware.com.0.0.34
spec:
  refName: kpack-dependencies.community.tanzu.vmware.com
  version: 0.0.34
  capacityRequirementsDescription: Registry with > 1GB available space
  releaseNotes: https://github.com/vmware-tanzu/package-for-kpack-dependencies/releases/tag/v0.0.34
  valuesSchema:
    openAPIv3:
      title: kpack-dependencies.community.tanzu.vmware.com values schema
      properties:
        kp_default_repository:
          type: string
          description: Docker repository for builder images. The same value used during installation of kpack.
          examples:
          - registry.io/kpack
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/kpack/dependencies@sha256:97f24c5f1ab602b5d0ae55a3f39432453e65a4682cbee31438c61a0f47ed0133
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
